config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :images
    resources :documents
    resources :pages
    resources :locations

    resources :blog_posts, :except => 'show'
    resources :topics, :except => 'show'
  end

  devise_for :users
  devise_scope :user do
    get "/login" => "devise/sessions#new", :as => :login
    delete "/logout" => "devise/sessions#destroy", :as => :logout
  end

  resources :topics, :only => %w{show index}

  root :to => 'static#index'

  get '/*permalink', :controller => :pages, :action => 'show'
end

app/views/admin/pages/_form.html.haml
= tinymce_assets

= form_for(@page, :url => url, :format => :html) do |f|
  = f.error_messages

  .form_section
    %h3 Visible Attributes

    = f.labeled_input :title, :comment => "Browser titlebar (optional)"
    = f.labeled_input :headline, :comment => "On-page headline (optional) "
    = f.labeled_input :permalink, :comment => "Url for this page (required)"
    -# it's enough to change this to a :published_start and :published_end
    -# field to enable that functionality for a CMS
    = f.labeled_input :published, :comment => "Uncheck to disable this page" do
      = f.check_box(:published)

  .form_section
    %h3 Invisible Attributes for Search Engines
    = f.labeled_input :keywords, :size => 80, :comment => "Comma-separated"
    = f.labeled_input :description do
      = f.text_area(:description, :size => "80x2")

  .form_section
    %h3 Page Content
    = f.labeled_input :content do
      = f.text_area(:content, :size => "80x40", :class => 'tinymce')
    = tinymce

  .form_section
    %h3 Advanced Options
    - if PAGE_LAYOUTS.size > 1
      .collapsed
        = f.labeled_input :layout, :text => "Section" do
          = f.select(:layout, PAGE_LAYOUTS)
    .collapsed
      = f.labeled_input :css, :text => 'CSS Styles' do
        = f.text_area(:css, :size => '80x8')
  = f.unlabeled_submit "Save Page"

app/views/admin/pages/edit.html.haml
- set_headline "Editing #{@human_name}: '#{@page.title}'"

= link_to 'Show', admin_page_path(@page)
|
= link_to 'Back to List', :action => :index

= render :partial => "form", :locals => {:url => url_for(:action => :update, :id => @page.id)}

app/views/admin/pages/index.html.haml
- set_headline "Listing pages"

= link_to 'New page', new_admin_page_path
%br

%table.listing
  %tr
    %th Published
    %th Title
    %th Path

  - @pages.each do |page|
    = content_tag_for :tr, page do
      %td= bool_checked page.published
      %td= link_to page.title, page_path(page)
      %td= page.permalink
      %td= link_to 'Edit', edit_admin_page_path(page)
      %td= link_to 'Delete', admin_page_path(page), :data => {:confirm => 'Are you sure?'}, :method => :delete

app/views/admin/pages/new.html.haml
- set_headline "New #@human_name"

= link_to 'Back to List', admin_pages_path

= render :partial => "form", :locals => {:url => url_for(:action => :create)}