config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :images
    resources :documents
    resources :pages
    resources :locations

    resources :blog_posts, :except => 'show'
    resources :topics, :except => 'show'
  end

  devise_for :users
  devise_scope :user do
    get "/login" => "devise/sessions#new", :as => :login
    delete "/logout" => "devise/sessions#destroy", :as => :logout
  end

  resources :topics, :only => %w{show index}

  root :to => 'static#index'

  get '/*permalink', :controller => :pages, :action => 'show'
end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id         :integer(4)      not null, primary key
#  name       :string(255)
#  path       :string(255)
#  parent_id  :integer(4)
#  lft        :integer(4)
#  rgt        :integer(4)
#  page_id    :integer(4)
#  created_at :datetime
#  updated_at :datetime
#
require 'absolute_path'

class Location < ActiveRecord::Base


  include AbsolutePath
  acts_as_nested_set

  belongs_to :page
  belongs_to :parent, :class_name => 'Location'

  validates_presence_of :name#, :path

  def resolved_path
    absolute_path(page ? page.permalink : path)
  end

  def self.topics_root
    find_or_create_by(:name => "Blog Topics")
  end

  scope :main_menu, -> do
    root.self_and_descendants
  end

  scope :blog_topics, -> do
    children_of(topics_root.id)
  end
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < Admin::AdminController
  # GET /locations
  def index
    @locations = location_scope
    @human_plural_name = human_plural_name
    @human_name = human_name
  end

  # GET /locations/new
  def new
    @location = Location.new()
    @location_scope = location_scope
    @human_name = human_name
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
    @location_scope = location_scope
    @human_name = human_name
  end

  # POST /locations
  def create
    @location = Location.new(location_params)

    if @location.save
      expire_locations_cache(@location)
      flash[:notice] = "#{human_name} was successfully created."
      if params[:from_page]
        redirect_to(edit_admin_page_path(:id => @location.page_id))
      else
        redirect_to(:action => :index)
      end
    else
      render :action => "new"
    end
  end


  # PUT /locations/1
  def update
    @location = Location.find(params[:id])

    expire_locations_cache(@location)
    unless (move_to = params[:location]["move_to"]).blank?
      Rails.logger.debug{"Moving [#{move_to}]: #{@location.to_text}"}
      if move_to == "last"
        @location.move_to_right_of(@location.siblings.last)
      else
        @location.move_to_left_of(move_to.to_i)
      end
      Rails.logger.debug{"Moved to #{@location.to_text}"}

      expire_locations_cache(@location)
    end

    if @location.update_attributes(location_params)
      flash[:notice] = "#{human_name} was successfully updated."
      redirect_to(:action => :index)
    else
      render :action => 'edit'
    end
  end

  # DELETE /locations/1
  def destroy
    @location = location_scope.find(params[:id])
    @location.destroy

    redirect_to(admin_locations_url)
  end

  private

  def human_plural_name
    "Menu Entries"
  end

  def human_name
    "Menu Entry"
  end

  def expire_locations_cache(location)
    location.self_and_ancestors.each do |root|
      NAV_TEMPLATE_NAMES.keys.each do |name|
        expire_fragment([:nav_menu, root.name, name] )
      end
    end
  end

  def location_scope
    Location.main_menu
  end

  def location_params
    params.required(:location).permit(:name, :path, :parent_id, :page_id, :parent, :page)
  end
end

app/helpers/admin/locations_helper.rb
module Admin::LocationsHelper
  def location_parent_selector(form)
    form.select(:parent_id,
      @location_scope.collect  {|p| [p.name, p.id]}, { :include_blank => "" }
    )
  end

  def sibling_selector(form)
    positions = [""]
    positions += @location.siblings.map {|sib| ["Before: " + sib.name, sib.id]}
    positions << ["Last", "last"]

    select_tag("location[move_to]", options_for_select(positions))
  end

  def page_selector(form)
    form.select(:page_id,
      Page.all.collect { |c| [c.title, c.id]}, { :include_blank => "" }
    )
  end

  def topic_selector(page)
    select_tag("page[topic_id]", options_from_collection_for_select(Location.blog_topics, "id", "name", @page_topic_id))
  end

  def list_tree(locations, add_depth = 0, selected_location_id = nil)
    str = ''
    [*locations].each do |location|
      Location.each_with_level(location.self_and_descendants) do |location, depth|
        str << (render :partial => "location", :locals => { :location => location,
                                                            :depth => (depth + add_depth),
                                                            :selected_location_id => selected_location_id})
      end
    end
    str.html_safe
  end

  def depth_indicator(depth)
    str = ''
    if depth > 0
      depth.times do
        str << image_tag("/images/icons/spacer.png", :class=> "inline", :size =>"20x12", :alt => "&nbsp;&nbsp;&nbsp;")
      end
      str << image_tag("/images/icons/indent_arrow.png", :class=>"inline", :size => "12x12", :alt => '->')
    end
    str.html_safe
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/admin/locations/_form.html.haml
:javascript
  $(function() {
      $("select#location_page_id ").change(function () {
          $("select#location_page_id option:selected").each(function() {
            if(!$(this).val()) {
                $("input#location_path").parent().show();
            } else {
                $("input#location_path").parent().hide();
            }
          });
      });

      if($("select#location_page_id option:selected").first().val()) {
          $("input#location_path").parent().hide();
      }
  });

= form_for([:admin,@location]) do |f|
  = f.error_messages
  = f.labeled_input :name
  = f.labeled_input :path
  = f.labeled_input :page_id do
    = page_selector(f)
  = f.labeled_input :parent_id do
    = location_parent_selector(f)
  - unless @location.new_record?
    = f.labeled_input :move_to do
      = sibling_selector(f)

  = f.unlabeled_submit "Save #{@human_name}"

app/views/admin/locations/_list_header.html.haml
%tr
  %th Name
  %th Parent
  %th Path or Page
  %th Tools

app/views/admin/locations/_location.html.haml
%tr{:id => "location_#{node.id.to_s}", :class => ('highlight' if defined?(selected_location_id) && selected_location_id.to_s == node.id.to_s)}
  %td
    = node.name
  %td= node.parent.name if node.parent
  %td
    - if node.page
      = link_to("Page: #{node.page.title}", '/'+node.page.permalink)
    - else
      - if node.path.blank?
        = link_to("Create Page", new_admin_page_path(:page => {:location_id => node.id}))
      -else
        = link_to("URL: #{node.path}", node.path)
  %td
    = link_to 'Create Child', new_admin_location_path(:node => {:parent_id => node.id})
    = link_to 'Edit', edit_admin_location_path(node)
    = link_to 'Delete', admin_location_path(node), :data => {:confirm => 'Are you sure?'}, :method => :delete
- if defined? children
  = children

app/views/admin/locations/edit.html.haml
- set_headline "Editing #{@human_name}"

= render :partial => 'form', :locals => { :action => :update }

= link_to 'Show', admin_location_path(@location)
= link_to 'Back', admin_locations_path

app/views/admin/locations/index.html.haml
- set_headline "List of #{@human_plural_name}"

%table.listing
  = render :partial => "list_header"
  = list_tree(:edit, @locations)

= link_to "New #{@human_name}", :action => :new

app/views/admin/locations/new.html.haml
- set_headline "New #{@human_name}"

= link_to 'Back to List', admin_locations_path

= render :partial => "form", :locals => {:action => :create}