config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :images
    resources :documents
    resources :pages
    resources :locations

    resources :blog_posts, :except => 'show'
    resources :topics, :except => 'show'
  end

  devise_for :users
  devise_scope :user do
    get "/login" => "devise/sessions#new", :as => :login
    delete "/logout" => "devise/sessions#destroy", :as => :logout
  end

  resources :topics, :only => %w{show index}

  root :to => 'static#index'

  get '/*permalink', :controller => :pages, :action => 'show'
end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id                 :integer          not null, primary key
#  image_file_name    :string(255)
#  image_file_size    :integer
#  image_content_type :string(255)
#  image_updated_at   :datetime
#  created_at         :datetime
#  updated_at         :datetime
#

class Image < ActiveRecord::Base

  mount_uploader :image, ImageUploader, :mount_on => :image_file_name
  validates_integrity_of :image
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::AdminController
  # GET /admin/upload/images
  def index
    @images = Image.all
  end

  # GET /admin/upload/images/1
  def show
    @image = Image.find(params[:id])
  end

  # GET /admin/upload/images/new
  def new
    @image = Image.new
  end

  # POST /admin/upload/images
  def create
    @image = Image.new(params[:image].permit(:image))

    if @image.save
      redirect_to(admin_image_path(@image), :notice => 'Image was successfully created.')
    else
      render :action => "new"
    end
  end

  # DELETE /admin/upload/images/1
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    redirect_to(admin_images_url)
  end
end

app/controllers/admin/upload/images_controller.rb
class Admin::Upload::ImagesController < Admin::AdminController
  # GET /admin/upload/images
  def index
    @images = Image.all
  end

  # GET /admin/upload/images/1
  def show
    @image = Image.find(params[:id])
  end

  # GET /admin/upload/images/new
  def new
    @image = Image.new
  end

  # POST /admin/upload/images
  def create
    @image = Image.new(params[:image].permit(:image))

    if @image.save
      redirect_to(admin_upload_image_path(@image), :notice => 'Image was successfully created.')
    else
      render :action => "new"
    end
  end

  # DELETE /admin/upload/images/1
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    redirect_to(admin_upload_images_url)
  end
end

app/views/admin/images/_form.html.haml
= form_for([:admin, @image], :html => {:multipart => true}) do |f|
  = f.file_field :image
  = f.error_messages

  = f.unlabeled_submit "Upload and Save Image"

app/views/admin/images/index.html.haml
- set_headline "Listing images"

= link_to 'New image', new_admin_image_path
%br

%table.listing
  %tr

  - for image in @images
    %tr
      %td= image_tag(image.image.url(:icon))
      %td= image.image_file_name
      %td= link_to 'Show', admin_image_path(image)
      %td= link_to 'Destroy', admin_image_path(image), :data => {:confirm => 'Are you sure?'}, :method => :delete

app/views/admin/images/new.html.haml
- set_headline "New image"

= link_to 'Back to List', admin_images_path

= render :partial => "admin/images/form"

app/views/admin/images/show.html.haml
- set_headline "Image: #{h @image.image.identifier}"

%table.listing.image-index
  - ImageUploader.versions.each_key do |style|
    %tr.uploaded_image{:id => style}
      %td.image-style
        = style.to_s.capitalize
        %p.dimensions
      %td
        %div.url-wrapper
          %input.image-url{:id => "fe_text_#{style}", :type => 'text', :value => @image.image.send(style).url, :size => 80}
          %button.my_clip_button{:id => "d_clip_button_#{style}", "data-clipboard-target" => "fe_text_#{style}", "data-clipboard-text" => "Default clipboard text from attribute", :title => "Click me to copy to clipboard."}
            %b Copy To Clipboard
        %div.arrow-right
        %div.image-partial
          = image_tag(@image.image.send(style).url)

= link_to 'Back', admin_images_path