config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :images
    resources :documents
    resources :pages
    resources :locations

    resources :blog_posts, :except => 'show'
    resources :topics, :except => 'show'
  end

  devise_for :users
  devise_scope :user do
    get "/login" => "devise/sessions#new", :as => :login
    delete "/logout" => "devise/sessions#destroy", :as => :logout
  end

  resources :topics, :only => %w{show index}

  root :to => 'static#index'

  get '/*permalink', :controller => :pages, :action => 'show'
end

app/controllers/admin/blog_post_controller.rb
class Admin::BlogPostController < Admin::PageController
  def create
    topic = Location.find(page_params[:topic_id])
    page_location = topic.children.create(:name => page_params[:title])
    page_params[:location_id] = page_location.id
    super
  end

  private

  def location_handling
    # A blog post *should* have exactly one Location associated, but it
    # *could* have multiple. Doesn't hurt to be conservative
    if @page.locations.present? and not @page.locations.any?{|location| location.parent.id == page_params[:topic_id]}
      @page.locations.first.move_to(page_params[:topic_id])
    end
  end

  def page_layout
    "blog"
  end

  def page_scope
    Page.blog
  end
end

app/controllers/admin/blog_posts_controller.rb
class Admin::BlogPostsController < Admin::PagesController
  def create
    super

    topic = Location.find(page_params[:topic_id])
    page_location = topic.children.create(:name => page_params[:title], :page => @page)
    page_location.save!
    page_params[:location_id] = page_location.id
  end

  private

  def human_name
    "Blog Post"
  end

  def location_handling
    # A blog post *should* have exactly one Location associated, but it
    # *could* have multiple. Doesn't hurt to be conservative
    if @page.locations.present? and not @page.locations.any?{|location| location.parent.id == page_params[:topic_id]}
      @page.locations.first.move_to_child_of(page_params[:topic_id])
    end
  end

  def page_layout
    "blog"
  end

  def page_scope
    Page.blog
  end
end

app/views/admin/blog_posts/_form.html.haml
= tinymce_assets

= form_for(@page, :url => url, :format => :html) do |f|
  = f.error_messages

  .form_section
    %h3 Visible Attributes

    = f.labeled_input :topic_id do
      = topic_selector(f)
    = f.labeled_input :title, :comment => "Browser titlebar (optional)"
    = f.labeled_input :permalink, :comment => "Url for this page (required)"
    -# it's enough to change this to a :published_start and :published_end
    -# field to enable that functionality for a CMS
    = f.labeled_input :published, :comment => "Uncheck to disable this page" do
      = f.check_box(:published)

  .form_section
    %h3 Invisible Attributes for Search Engines
    = f.labeled_input :keywords, :size => 80, :comment => "Comma-separated"
    = f.labeled_input :description do
      = f.text_area(:description, :size => "80x2")

  .form_section
    %h3 Page Content
    %h4 On-page headline (large type):
    = f.labeled_input :headline do
      = f.text_area(:headline, :size => "80x2")

    %h4 Main content
    = f.labeled_input :content do
      = f.text_area(:content, :size => "80x40", :class => 'tinymce')
    = tinymce

  .form_section
    %h3 Advanced Options
    .collapsed
      = f.labeled_input :css, :text => 'CSS Styles' do
        = f.text_area(:css, :size => '80x8')
  = f.unlabeled_submit "Save Blog Post"

app/views/admin/blog_posts/index.html.haml
- set_headline "Listing Blog Posts"

= link_to 'New Blog Post', new_admin_blog_post_path
%br

%table.listing
  %tr
    %th Published
    %th Title
    %th Path

  - @pages.each do |page|
    = content_tag_for :tr, page do
      %td= bool_checked page.published
      %td= link_to page.title, page_path(page)
      %td= page.permalink
      %td= link_to 'Edit', edit_admin_blog_post_path(page)
      %td= link_to 'Delete', admin_blog_post_path(page), :data => {:confirm => 'Are you sure?'}, :method => :delete